# taken from https://github.com/grpc-ecosystem/grpc-gateway/blob/b7c42d065e726b50ea642eb63f29944629341dcc/examples/internal/proto/examplepb/unannotated_echo_service.swagger.yaml
# reference: https://github.com/grpc-ecosystem/grpc-gateway/blob/b7c42d065e726b50ea642eb63f29944629341dcc/protoc-gen-openapiv2/options/openapiv2.proto
openapiOptions:
  file:
    # the file name must be the same as one passed to protoc when generating .swagger.json
    - file: "features.proto"
      option:
        info:
          title: Feature Request API
          description: A simple API for managing feature requests with voting functionality
          version: 1.0.0
