// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: features.proto

package pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a detailed feature.
type Feature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id
	//
	// Unique identifier for the feature
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Title
	//
	// Feature title
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Description
	//
	// Detailed description of the feature
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Details
	//
	// Detailed implementation notes for the feature
	Details string `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	// Upvotes
	//
	// Number of upvotes received
	Upvotes int32 `protobuf:"varint,5,opt,name=upvotes,proto3" json:"upvotes,omitempty"`
	// Completed
	//
	// Whether the feature has been completed
	Completed     bool `protobuf:"varint,6,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feature) Reset() {
	*x = Feature{}
	mi := &file_features_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feature) ProtoMessage() {}

func (x *Feature) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feature.ProtoReflect.Descriptor instead.
func (*Feature) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{0}
}

func (x *Feature) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Feature) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Feature) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Feature) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *Feature) GetUpvotes() int32 {
	if x != nil {
		return x.Upvotes
	}
	return 0
}

func (x *Feature) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

// Represents a summary of a feature.
type FeatureSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id
	//
	// Unique identifier for the feature
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Title
	//
	// Feature title
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Upvotes
	//
	// Number of upvotes received
	Upvotes int32 `protobuf:"varint,3,opt,name=upvotes,proto3" json:"upvotes,omitempty"`
	// Completed
	//
	// Whether the feature has been completed
	Completed     bool `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureSummary) Reset() {
	*x = FeatureSummary{}
	mi := &file_features_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureSummary) ProtoMessage() {}

func (x *FeatureSummary) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureSummary.ProtoReflect.Descriptor instead.
func (*FeatureSummary) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{1}
}

func (x *FeatureSummary) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FeatureSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FeatureSummary) GetUpvotes() int32 {
	if x != nil {
		return x.Upvotes
	}
	return 0
}

func (x *FeatureSummary) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

// Request to get a single feature.
type GetFeatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeatureRequest) Reset() {
	*x = GetFeatureRequest{}
	mi := &file_features_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeatureRequest) ProtoMessage() {}

func (x *GetFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeatureRequest.ProtoReflect.Descriptor instead.
func (*GetFeatureRequest) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{2}
}

func (x *GetFeatureRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Request to add a new feature.
type AddFeatureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Title
	//
	// Feature title
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Description
	//
	// Detailed description of the feature
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Details
	//
	// Detailed implementation notes for the feature
	Details       string `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFeatureRequest) Reset() {
	*x = AddFeatureRequest{}
	mi := &file_features_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFeatureRequest) ProtoMessage() {}

func (x *AddFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFeatureRequest.ProtoReflect.Descriptor instead.
func (*AddFeatureRequest) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{3}
}

func (x *AddFeatureRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddFeatureRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddFeatureRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// Request to vote for a feature.
type VoteFeatureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Feature ID
	//
	// ID of the feature to vote for
	Id            int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteFeatureRequest) Reset() {
	*x = VoteFeatureRequest{}
	mi := &file_features_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteFeatureRequest) ProtoMessage() {}

func (x *VoteFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteFeatureRequest.ProtoReflect.Descriptor instead.
func (*VoteFeatureRequest) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{4}
}

func (x *VoteFeatureRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Request to mark a feature as complete.
type CompleteFeatureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Feature ID
	//
	// ID of the feature to mark as completed
	Id            int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteFeatureRequest) Reset() {
	*x = CompleteFeatureRequest{}
	mi := &file_features_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteFeatureRequest) ProtoMessage() {}

func (x *CompleteFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteFeatureRequest.ProtoReflect.Descriptor instead.
func (*CompleteFeatureRequest) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteFeatureRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Request to delete a feature.
type DeleteFeatureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Feature ID
	//
	// Feature ID to delete
	Id            int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFeatureRequest) Reset() {
	*x = DeleteFeatureRequest{}
	mi := &file_features_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFeatureRequest) ProtoMessage() {}

func (x *DeleteFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFeatureRequest.ProtoReflect.Descriptor instead.
func (*DeleteFeatureRequest) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFeatureRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Response for ListFeatures RPC.
type ListFeaturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summaries     []*FeatureSummary      `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeaturesResponse) Reset() {
	*x = ListFeaturesResponse{}
	mi := &file_features_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeaturesResponse) ProtoMessage() {}

func (x *ListFeaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeaturesResponse.ProtoReflect.Descriptor instead.
func (*ListFeaturesResponse) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{7}
}

func (x *ListFeaturesResponse) GetSummaries() []*FeatureSummary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

var File_features_proto protoreflect.FileDescriptor

const file_features_proto_rawDesc = "" +
	"\n" +
	"\x0efeatures.proto\x12\bfeatures\x1a\x1bgoogle/protobuf/empty.proto\"\xa3\x01\n" +
	"\aFeature\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\x12\x18\n" +
	"\aupvotes\x18\x05 \x01(\x05R\aupvotes\x12\x1c\n" +
	"\tcompleted\x18\x06 \x01(\bR\tcompleted\"n\n" +
	"\x0eFeatureSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\aupvotes\x18\x03 \x01(\x05R\aupvotes\x12\x1c\n" +
	"\tcompleted\x18\x04 \x01(\bR\tcompleted\"#\n" +
	"\x11GetFeatureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"e\n" +
	"\x11AddFeatureRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"$\n" +
	"\x12VoteFeatureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"(\n" +
	"\x16CompleteFeatureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"&\n" +
	"\x14DeleteFeatureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"N\n" +
	"\x14ListFeaturesResponse\x126\n" +
	"\tsummaries\x18\x01 \x03(\v2\x18.features.FeatureSummaryR\tsummaries2\xf6\x03\n" +
	"\x0eFeatureService\x12H\n" +
	"\fListFeatures\x12\x16.google.protobuf.Empty\x1a\x1e.features.ListFeaturesResponse\"\x00\x12C\n" +
	"\rGetTopFeature\x12\x16.google.protobuf.Empty\x1a\x18.features.FeatureSummary\"\x00\x12>\n" +
	"\n" +
	"GetFeature\x12\x1b.features.GetFeatureRequest\x1a\x11.features.Feature\"\x00\x12>\n" +
	"\n" +
	"AddFeature\x12\x1b.features.AddFeatureRequest\x1a\x11.features.Feature\"\x00\x12@\n" +
	"\vVoteFeature\x12\x1c.features.VoteFeatureRequest\x1a\x11.features.Feature\"\x00\x12H\n" +
	"\x0fCompleteFeature\x12 .features.CompleteFeatureRequest\x1a\x11.features.Feature\"\x00\x12I\n" +
	"\rDeleteFeature\x12\x1e.features.DeleteFeatureRequest\x1a\x16.google.protobuf.Empty\"\x00B1Z/github.com/genmcp/grpc-demo/000_grpc_server/pkgb\x06proto3"

var (
	file_features_proto_rawDescOnce sync.Once
	file_features_proto_rawDescData []byte
)

func file_features_proto_rawDescGZIP() []byte {
	file_features_proto_rawDescOnce.Do(func() {
		file_features_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_features_proto_rawDesc), len(file_features_proto_rawDesc)))
	})
	return file_features_proto_rawDescData
}

var file_features_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_features_proto_goTypes = []any{
	(*Feature)(nil),                // 0: features.Feature
	(*FeatureSummary)(nil),         // 1: features.FeatureSummary
	(*GetFeatureRequest)(nil),      // 2: features.GetFeatureRequest
	(*AddFeatureRequest)(nil),      // 3: features.AddFeatureRequest
	(*VoteFeatureRequest)(nil),     // 4: features.VoteFeatureRequest
	(*CompleteFeatureRequest)(nil), // 5: features.CompleteFeatureRequest
	(*DeleteFeatureRequest)(nil),   // 6: features.DeleteFeatureRequest
	(*ListFeaturesResponse)(nil),   // 7: features.ListFeaturesResponse
	(*emptypb.Empty)(nil),          // 8: google.protobuf.Empty
}
var file_features_proto_depIdxs = []int32{
	1, // 0: features.ListFeaturesResponse.summaries:type_name -> features.FeatureSummary
	8, // 1: features.FeatureService.ListFeatures:input_type -> google.protobuf.Empty
	8, // 2: features.FeatureService.GetTopFeature:input_type -> google.protobuf.Empty
	2, // 3: features.FeatureService.GetFeature:input_type -> features.GetFeatureRequest
	3, // 4: features.FeatureService.AddFeature:input_type -> features.AddFeatureRequest
	4, // 5: features.FeatureService.VoteFeature:input_type -> features.VoteFeatureRequest
	5, // 6: features.FeatureService.CompleteFeature:input_type -> features.CompleteFeatureRequest
	6, // 7: features.FeatureService.DeleteFeature:input_type -> features.DeleteFeatureRequest
	7, // 8: features.FeatureService.ListFeatures:output_type -> features.ListFeaturesResponse
	1, // 9: features.FeatureService.GetTopFeature:output_type -> features.FeatureSummary
	0, // 10: features.FeatureService.GetFeature:output_type -> features.Feature
	0, // 11: features.FeatureService.AddFeature:output_type -> features.Feature
	0, // 12: features.FeatureService.VoteFeature:output_type -> features.Feature
	0, // 13: features.FeatureService.CompleteFeature:output_type -> features.Feature
	8, // 14: features.FeatureService.DeleteFeature:output_type -> google.protobuf.Empty
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_features_proto_init() }
func file_features_proto_init() {
	if File_features_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_features_proto_rawDesc), len(file_features_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_features_proto_goTypes,
		DependencyIndexes: file_features_proto_depIdxs,
		MessageInfos:      file_features_proto_msgTypes,
	}.Build()
	File_features_proto = out.File
	file_features_proto_goTypes = nil
	file_features_proto_depIdxs = nil
}
